import numpy as np
import matplotlib.pyplot as plt
import os

# ============================================================
# SETTINGS
# ============================================================

# Use the filenames generated by the previous extraction script
FILES = [
    "results_tomography_10_bits.npz",
    "results_tomography_25_bits.npz",
    "results_tomography_50_bits.npz"
]

# ============================================================
# PHASE 1: CLICK THRESHOLDS (USING FIRST FILE)
# ============================================================

first_file = FILES[0]
print(f"Loading {first_file} for threshold selection...")

data = np.load(first_file, allow_pickle=True)
time = data["time"]
intensities = data["intensities"]

# Handle custom labels if they exist from the previous script
try:
    roi_labels = data["roi_labels"]
except KeyError:
    roi_labels = [f"ROI {i + 1}" for i in range(len(intensities))]

num_rois = len(intensities)
print(f"Loaded {num_rois} ROIs.")

thresholds = []

for roi_idx in range(num_rois):
    fig, ax = plt.subplots(figsize=(12, 4))
    ax.plot(time, intensities[roi_idx])

    label = roi_labels[roi_idx]
    ax.set_title(f"{label} ({first_file})\nClick once to choose threshold")
    ax.set_xlabel("Time (s)")
    ax.set_ylabel("Integrated Intensity")
    ax.grid(True)

    point = plt.ginput(1, timeout=-1)
    threshold = point[0][1]
    thresholds.append(threshold)

    ax.axhline(
        threshold,
        linestyle="--",
        linewidth=2,
        color="red",
        label=f"Threshold = {threshold:.1f}"
    )
    ax.legend()
    plt.show()

print("\nSelected thresholds locked in:")
for i, th in enumerate(thresholds):
    print(f"{roi_labels[i]}: {th:.2f}")

# ============================================================
# PHASE 2: BINARIZE AND SAVE ALL FILES
# ============================================================

print("\nProcessing and saving all files...")

for file_name in FILES:

    if not os.path.exists(file_name):
        print(f"Warning: {file_name} not found. Skipping.")
        continue

    print(f"Binarizing {file_name}...")

    file_data = np.load(file_name, allow_pickle=True)
    f_time = file_data["time"]
    f_intensities = file_data["intensities"]

    binary_signals = []

    for i in range(num_rois):
        binary = (f_intensities[i] > thresholds[i]).astype(int)
        binary_signals.append(binary)

    measurement_matrix = np.column_stack(binary_signals)

    save_name = f"thresholded_{file_name}"

    np.savez(
        save_name,
        time=f_time,
        intensities=f_intensities,
        thresholds=thresholds,
        binary_signals=binary_signals,
        measurement_matrix=measurement_matrix,
        roi_labels=roi_labels
    )

print("\nAll Tomography files thresholded and saved.")